# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from eigen.internal.v1 import compilation_service_pb2 as eigen_dot_internal_dot_v1_dot_compilation__service__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in eigen/internal/v1/compilation_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CompilationServiceStub:
    """Internal compilation service contract.
    Source of truth: RFC 0004 (CompilationService) + reference docs.

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CompileCircuit = channel.unary_unary(
                '/eigen.internal.v1.CompilationService/CompileCircuit',
                request_serializer=eigen_dot_internal_dot_v1_dot_compilation__service__pb2.CompileCircuitRequest.SerializeToString,
                response_deserializer=eigen_dot_internal_dot_v1_dot_compilation__service__pb2.CompileCircuitResponse.FromString,
                _registered_method=True)
        self.CompileJob = channel.unary_unary(
                '/eigen.internal.v1.CompilationService/CompileJob',
                request_serializer=eigen_dot_internal_dot_v1_dot_compilation__service__pb2.CompileJobRequest.SerializeToString,
                response_deserializer=eigen_dot_internal_dot_v1_dot_compilation__service__pb2.CompileJobResponse.FromString,
                _registered_method=True)
        self.OptimizeCircuit = channel.unary_unary(
                '/eigen.internal.v1.CompilationService/OptimizeCircuit',
                request_serializer=eigen_dot_internal_dot_v1_dot_compilation__service__pb2.OptimizeCircuitRequest.SerializeToString,
                response_deserializer=eigen_dot_internal_dot_v1_dot_compilation__service__pb2.OptimizeCircuitResponse.FromString,
                _registered_method=True)
        self.ValidateCircuit = channel.unary_unary(
                '/eigen.internal.v1.CompilationService/ValidateCircuit',
                request_serializer=eigen_dot_internal_dot_v1_dot_compilation__service__pb2.ValidateCircuitRequest.SerializeToString,
                response_deserializer=eigen_dot_internal_dot_v1_dot_compilation__service__pb2.ValidateCircuitResponse.FromString,
                _registered_method=True)


class CompilationServiceServicer:
    """Internal compilation service contract.
    Source of truth: RFC 0004 (CompilationService) + reference docs.

    """

    def CompileCircuit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompileJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OptimizeCircuit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateCircuit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CompilationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CompileCircuit': grpc.unary_unary_rpc_method_handler(
                    servicer.CompileCircuit,
                    request_deserializer=eigen_dot_internal_dot_v1_dot_compilation__service__pb2.CompileCircuitRequest.FromString,
                    response_serializer=eigen_dot_internal_dot_v1_dot_compilation__service__pb2.CompileCircuitResponse.SerializeToString,
            ),
            'CompileJob': grpc.unary_unary_rpc_method_handler(
                    servicer.CompileJob,
                    request_deserializer=eigen_dot_internal_dot_v1_dot_compilation__service__pb2.CompileJobRequest.FromString,
                    response_serializer=eigen_dot_internal_dot_v1_dot_compilation__service__pb2.CompileJobResponse.SerializeToString,
            ),
            'OptimizeCircuit': grpc.unary_unary_rpc_method_handler(
                    servicer.OptimizeCircuit,
                    request_deserializer=eigen_dot_internal_dot_v1_dot_compilation__service__pb2.OptimizeCircuitRequest.FromString,
                    response_serializer=eigen_dot_internal_dot_v1_dot_compilation__service__pb2.OptimizeCircuitResponse.SerializeToString,
            ),
            'ValidateCircuit': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateCircuit,
                    request_deserializer=eigen_dot_internal_dot_v1_dot_compilation__service__pb2.ValidateCircuitRequest.FromString,
                    response_serializer=eigen_dot_internal_dot_v1_dot_compilation__service__pb2.ValidateCircuitResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'eigen.internal.v1.CompilationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('eigen.internal.v1.CompilationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CompilationService:
    """Internal compilation service contract.
    Source of truth: RFC 0004 (CompilationService) + reference docs.

    """

    @staticmethod
    def CompileCircuit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/eigen.internal.v1.CompilationService/CompileCircuit',
            eigen_dot_internal_dot_v1_dot_compilation__service__pb2.CompileCircuitRequest.SerializeToString,
            eigen_dot_internal_dot_v1_dot_compilation__service__pb2.CompileCircuitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CompileJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/eigen.internal.v1.CompilationService/CompileJob',
            eigen_dot_internal_dot_v1_dot_compilation__service__pb2.CompileJobRequest.SerializeToString,
            eigen_dot_internal_dot_v1_dot_compilation__service__pb2.CompileJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OptimizeCircuit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/eigen.internal.v1.CompilationService/OptimizeCircuit',
            eigen_dot_internal_dot_v1_dot_compilation__service__pb2.OptimizeCircuitRequest.SerializeToString,
            eigen_dot_internal_dot_v1_dot_compilation__service__pb2.OptimizeCircuitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateCircuit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/eigen.internal.v1.CompilationService/ValidateCircuit',
            eigen_dot_internal_dot_v1_dot_compilation__service__pb2.ValidateCircuitRequest.SerializeToString,
            eigen_dot_internal_dot_v1_dot_compilation__service__pb2.ValidateCircuitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
