# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: eigen/internal/v1/types.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'eigen/internal/v1/types.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1d\x65igen/internal/v1/types.proto\x12\x11\x65igen.internal.v1\"P\n\x0e\x43ircuitPayload\x12\x30\n\x06\x66ormat\x18\x01 \x01(\x0e\x32 .eigen.internal.v1.CircuitFormat\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\"\xa1\x02\n\nDeviceInfo\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x14\n\x0c\x62\x61\x63kend_type\x18\x03 \x01(\t\x12/\n\x06status\x18\x04 \x01(\x0e\x32\x1f.eigen.internal.v1.DeviceStatus\x12\x13\n\x0bqueue_depth\x18\x05 \x01(\x05\x12\x1a\n\x12\x65stimated_wait_sec\x18\x06 \x01(\x05\x12\x45\n\x0c\x63\x61pabilities\x18\x07 \x03(\x0b\x32/.eigen.internal.v1.DeviceInfo.CapabilitiesEntry\x1a\x33\n\x11\x43\x61pabilitiesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01*\xac\x01\n\rCircuitFormat\x12\x1e\n\x1a\x43IRCUIT_FORMAT_UNSPECIFIED\x10\x00\x12\x1b\n\x17\x43IRCUIT_FORMAT_AQO_JSON\x10\x01\x12\x1c\n\x18\x43IRCUIT_FORMAT_AQO_PROTO\x10\x02\x12\x1d\n\x19\x43IRCUIT_FORMAT_QASM3_TEXT\x10\x03\x12!\n\x1d\x43IRCUIT_FORMAT_BACKEND_NATIVE\x10\x04*\xc0\x01\n\x0c\x44\x65viceStatus\x12\x1d\n\x19\x44\x45VICE_STATUS_UNSPECIFIED\x10\x00\x12\x18\n\x14\x44\x45VICE_STATUS_ONLINE\x10\x01\x12\x19\n\x15\x44\x45VICE_STATUS_OFFLINE\x10\x02\x12\x1d\n\x19\x44\x45VICE_STATUS_CALIBRATING\x10\x03\x12\x1d\n\x19\x44\x45VICE_STATUS_MAINTENANCE\x10\x04\x12\x1e\n\x1a\x44\x45VICE_STATUS_ERROR_STATUS\x10\x05\x42g\n\x19\x63om.eigen.api.internal.v1B\x12InternalTypesProtoP\x01Z4github.com/eigen-os/eigen/api/internal/v1;internalv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'eigen.internal.v1.types_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\031com.eigen.api.internal.v1B\022InternalTypesProtoP\001Z4github.com/eigen-os/eigen/api/internal/v1;internalv1'
  _globals['_DEVICEINFO_CAPABILITIESENTRY']._loaded_options = None
  _globals['_DEVICEINFO_CAPABILITIESENTRY']._serialized_options = b'8\001'
  _globals['_CIRCUITFORMAT']._serialized_start=427
  _globals['_CIRCUITFORMAT']._serialized_end=599
  _globals['_DEVICESTATUS']._serialized_start=602
  _globals['_DEVICESTATUS']._serialized_end=794
  _globals['_CIRCUITPAYLOAD']._serialized_start=52
  _globals['_CIRCUITPAYLOAD']._serialized_end=132
  _globals['_DEVICEINFO']._serialized_start=135
  _globals['_DEVICEINFO']._serialized_end=424
  _globals['_DEVICEINFO_CAPABILITIESENTRY']._serialized_start=373
  _globals['_DEVICEINFO_CAPABILITIESENTRY']._serialized_end=424
# @@protoc_insertion_point(module_scope)
