apiVersion: eigen.os/v0.1
kind: QuantumJob
metadata:
  name: vqe-basic-2q
  labels:
    example: 'true'
    algorithm: vqe
spec:
  program_path: program.eigen.py
  entrypoint: main
  target: sim:local
  priority: 90
  metadata:
    shots: '8192'
    max_iters: '100'
    optimizer: cobyla
