apiVersion: eigen.os/v0.1
kind: QuantumJob
metadata:
  name: vqe-basic-2q
  labels:
    example: "true"
    algorithm: "vqe"
spec:
  program_path: program.eigen.py
  entrypoint: main
  target: sim:local
  priority: 50
  metadata:
    shots: "1024"
    max_iters: "25"
    optimizer: "cobyla"