# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from eigen_internal.v1 import driver_manager_service_pb2 as eigen__internal_dot_v1_dot_driver__manager__service__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in eigen_internal/v1/driver_manager_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DriverManagerServiceStub(object):
    """Kernel-facing driver manager contract.
    Source of truth: RFC 0006.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListDevices = channel.unary_unary(
                '/eigen.internal.v1.DriverManagerService/ListDevices',
                request_serializer=eigen__internal_dot_v1_dot_driver__manager__service__pb2.ListDevicesRequest.SerializeToString,
                response_deserializer=eigen__internal_dot_v1_dot_driver__manager__service__pb2.ListDevicesResponse.FromString,
                _registered_method=True)
        self.GetDeviceStatus = channel.unary_unary(
                '/eigen.internal.v1.DriverManagerService/GetDeviceStatus',
                request_serializer=eigen__internal_dot_v1_dot_driver__manager__service__pb2.DeviceStatusRequest.SerializeToString,
                response_deserializer=eigen__internal_dot_v1_dot_driver__manager__service__pb2.DeviceStatusResponse.FromString,
                _registered_method=True)
        self.ExecuteCircuit = channel.unary_unary(
                '/eigen.internal.v1.DriverManagerService/ExecuteCircuit',
                request_serializer=eigen__internal_dot_v1_dot_driver__manager__service__pb2.ExecuteCircuitRequest.SerializeToString,
                response_deserializer=eigen__internal_dot_v1_dot_driver__manager__service__pb2.ExecuteCircuitResponse.FromString,
                _registered_method=True)
        self.CalibrateDevice = channel.unary_unary(
                '/eigen.internal.v1.DriverManagerService/CalibrateDevice',
                request_serializer=eigen__internal_dot_v1_dot_driver__manager__service__pb2.CalibrateDeviceRequest.SerializeToString,
                response_deserializer=eigen__internal_dot_v1_dot_driver__manager__service__pb2.CalibrateDeviceResponse.FromString,
                _registered_method=True)


class DriverManagerServiceServicer(object):
    """Kernel-facing driver manager contract.
    Source of truth: RFC 0006.
    """

    def ListDevices(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDeviceStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteCircuit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CalibrateDevice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DriverManagerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListDevices': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDevices,
                    request_deserializer=eigen__internal_dot_v1_dot_driver__manager__service__pb2.ListDevicesRequest.FromString,
                    response_serializer=eigen__internal_dot_v1_dot_driver__manager__service__pb2.ListDevicesResponse.SerializeToString,
            ),
            'GetDeviceStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDeviceStatus,
                    request_deserializer=eigen__internal_dot_v1_dot_driver__manager__service__pb2.DeviceStatusRequest.FromString,
                    response_serializer=eigen__internal_dot_v1_dot_driver__manager__service__pb2.DeviceStatusResponse.SerializeToString,
            ),
            'ExecuteCircuit': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteCircuit,
                    request_deserializer=eigen__internal_dot_v1_dot_driver__manager__service__pb2.ExecuteCircuitRequest.FromString,
                    response_serializer=eigen__internal_dot_v1_dot_driver__manager__service__pb2.ExecuteCircuitResponse.SerializeToString,
            ),
            'CalibrateDevice': grpc.unary_unary_rpc_method_handler(
                    servicer.CalibrateDevice,
                    request_deserializer=eigen__internal_dot_v1_dot_driver__manager__service__pb2.CalibrateDeviceRequest.FromString,
                    response_serializer=eigen__internal_dot_v1_dot_driver__manager__service__pb2.CalibrateDeviceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'eigen.internal.v1.DriverManagerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('eigen.internal.v1.DriverManagerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DriverManagerService(object):
    """Kernel-facing driver manager contract.
    Source of truth: RFC 0006.
    """

    @staticmethod
    def ListDevices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/eigen.internal.v1.DriverManagerService/ListDevices',
            eigen__internal_dot_v1_dot_driver__manager__service__pb2.ListDevicesRequest.SerializeToString,
            eigen__internal_dot_v1_dot_driver__manager__service__pb2.ListDevicesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDeviceStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/eigen.internal.v1.DriverManagerService/GetDeviceStatus',
            eigen__internal_dot_v1_dot_driver__manager__service__pb2.DeviceStatusRequest.SerializeToString,
            eigen__internal_dot_v1_dot_driver__manager__service__pb2.DeviceStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteCircuit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/eigen.internal.v1.DriverManagerService/ExecuteCircuit',
            eigen__internal_dot_v1_dot_driver__manager__service__pb2.ExecuteCircuitRequest.SerializeToString,
            eigen__internal_dot_v1_dot_driver__manager__service__pb2.ExecuteCircuitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CalibrateDevice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/eigen.internal.v1.DriverManagerService/CalibrateDevice',
            eigen__internal_dot_v1_dot_driver__manager__service__pb2.CalibrateDeviceRequest.SerializeToString,
            eigen__internal_dot_v1_dot_driver__manager__service__pb2.CalibrateDeviceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
