# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: eigen_internal/v1/types.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'eigen_internal/v1/types.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1d\x65igen_internal/v1/types.proto\x12\x11\x65igen.internal.v1\"P\n\x0e\x43ircuitPayload\x12\x30\n\x06\x66ormat\x18\x01 \x01(\x0e\x32 .eigen.internal.v1.CircuitFormat\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\"\xa1\x02\n\nDeviceInfo\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x14\n\x0c\x62\x61\x63kend_type\x18\x03 \x01(\t\x12/\n\x06status\x18\x04 \x01(\x0e\x32\x1f.eigen.internal.v1.DeviceStatus\x12\x13\n\x0bqueue_depth\x18\x05 \x01(\x05\x12\x1a\n\x12\x65stimated_wait_sec\x18\x06 \x01(\x05\x12\x45\n\x0c\x63\x61pabilities\x18\x07 \x03(\x0b\x32/.eigen.internal.v1.DeviceInfo.CapabilitiesEntry\x1a\x33\n\x11\x43\x61pabilitiesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01*p\n\rCircuitFormat\x12\x1e\n\x1a\x43IRCUIT_FORMAT_UNSPECIFIED\x10\x00\x12\x0c\n\x08\x41QO_JSON\x10\x01\x12\r\n\tAQO_PROTO\x10\x02\x12\x0e\n\nQASM3_TEXT\x10\x03\x12\x12\n\x0e\x42\x41\x43KEND_NATIVE\x10\x04*z\n\x0c\x44\x65viceStatus\x12\x1d\n\x19\x44\x45VICE_STATUS_UNSPECIFIED\x10\x00\x12\n\n\x06ONLINE\x10\x01\x12\x0b\n\x07OFFLINE\x10\x02\x12\x0f\n\x0b\x43\x41LIBRATING\x10\x03\x12\x0f\n\x0bMAINTENANCE\x10\x04\x12\x10\n\x0c\x45RROR_STATUS\x10\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'eigen_internal.v1.types_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DEVICEINFO_CAPABILITIESENTRY']._loaded_options = None
  _globals['_DEVICEINFO_CAPABILITIESENTRY']._serialized_options = b'8\001'
  _globals['_CIRCUITFORMAT']._serialized_start=426
  _globals['_CIRCUITFORMAT']._serialized_end=538
  _globals['_DEVICESTATUS']._serialized_start=540
  _globals['_DEVICESTATUS']._serialized_end=662
  _globals['_CIRCUITPAYLOAD']._serialized_start=52
  _globals['_CIRCUITPAYLOAD']._serialized_end=132
  _globals['_DEVICEINFO']._serialized_start=135
  _globals['_DEVICEINFO']._serialized_end=424
  _globals['_DEVICEINFO_CAPABILITIESENTRY']._serialized_start=373
  _globals['_DEVICEINFO_CAPABILITIESENTRY']._serialized_end=424
# @@protoc_insertion_point(module_scope)
