# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from eigen.internal.v1 import kernel_gateway_pb2 as eigen_dot_internal_dot_v1_dot_kernel__gateway__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in eigen/internal/v1/kernel_gateway_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class KernelGatewayServiceStub:
    """Product 1.0 Wave 2 internal gateway between System API and Kernel.
    Kernel/QRTX is the canonical lifecycle authority.
    Source of truth: RFC 0050, docs/reference/api/grpc-internal.md
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EnqueueJob = channel.unary_unary(
                '/eigen.internal.v1.KernelGatewayService/EnqueueJob',
                request_serializer=eigen_dot_internal_dot_v1_dot_kernel__gateway__pb2.EnqueueJobRequest.SerializeToString,
                response_deserializer=eigen_dot_internal_dot_v1_dot_kernel__gateway__pb2.EnqueueJobResponse.FromString,
                _registered_method=True)
        self.GetJobStatus = channel.unary_unary(
                '/eigen.internal.v1.KernelGatewayService/GetJobStatus',
                request_serializer=eigen_dot_internal_dot_v1_dot_kernel__gateway__pb2.GetJobStatusRequest.SerializeToString,
                response_deserializer=eigen_dot_internal_dot_v1_dot_kernel__gateway__pb2.GetJobStatusResponse.FromString,
                _registered_method=True)
        self.CancelJob = channel.unary_unary(
                '/eigen.internal.v1.KernelGatewayService/CancelJob',
                request_serializer=eigen_dot_internal_dot_v1_dot_kernel__gateway__pb2.CancelJobRequest.SerializeToString,
                response_deserializer=eigen_dot_internal_dot_v1_dot_kernel__gateway__pb2.CancelJobResponse.FromString,
                _registered_method=True)
        self.GetJobResults = channel.unary_unary(
                '/eigen.internal.v1.KernelGatewayService/GetJobResults',
                request_serializer=eigen_dot_internal_dot_v1_dot_kernel__gateway__pb2.GetJobResultsRequest.SerializeToString,
                response_deserializer=eigen_dot_internal_dot_v1_dot_kernel__gateway__pb2.GetJobResultsResponse.FromString,
                _registered_method=True)
        self.StreamJobUpdates = channel.unary_stream(
                '/eigen.internal.v1.KernelGatewayService/StreamJobUpdates',
                request_serializer=eigen_dot_internal_dot_v1_dot_kernel__gateway__pb2.StreamJobUpdatesRequest.SerializeToString,
                response_deserializer=eigen_dot_internal_dot_v1_dot_kernel__gateway__pb2.StreamJobUpdatesResponse.FromString,
                _registered_method=True)
        self.GetDispatchRationale = channel.unary_unary(
                '/eigen.internal.v1.KernelGatewayService/GetDispatchRationale',
                request_serializer=eigen_dot_internal_dot_v1_dot_kernel__gateway__pb2.GetDispatchRationaleRequest.SerializeToString,
                response_deserializer=eigen_dot_internal_dot_v1_dot_kernel__gateway__pb2.GetDispatchRationaleResponse.FromString,
                _registered_method=True)


class KernelGatewayServiceServicer:
    """Product 1.0 Wave 2 internal gateway between System API and Kernel.
    Kernel/QRTX is the canonical lifecycle authority.
    Source of truth: RFC 0050, docs/reference/api/grpc-internal.md
    """

    def EnqueueJob(self, request, context):
        """Enqueue a job for orchestration.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetJobStatus(self, request, context):
        """Get current job status.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelJob(self, request, context):
        """Cancel a running or queued job.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetJobResults(self, request, context):
        """Retrieve job results and references.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamJobUpdates(self, request, context):
        """Stream job updates with heartbeat and deterministic ordering.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDispatchRationale(self, request, context):
        """Get dispatch rationale and scheduling decision metadata.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KernelGatewayServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EnqueueJob': grpc.unary_unary_rpc_method_handler(
                    servicer.EnqueueJob,
                    request_deserializer=eigen_dot_internal_dot_v1_dot_kernel__gateway__pb2.EnqueueJobRequest.FromString,
                    response_serializer=eigen_dot_internal_dot_v1_dot_kernel__gateway__pb2.EnqueueJobResponse.SerializeToString,
            ),
            'GetJobStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetJobStatus,
                    request_deserializer=eigen_dot_internal_dot_v1_dot_kernel__gateway__pb2.GetJobStatusRequest.FromString,
                    response_serializer=eigen_dot_internal_dot_v1_dot_kernel__gateway__pb2.GetJobStatusResponse.SerializeToString,
            ),
            'CancelJob': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelJob,
                    request_deserializer=eigen_dot_internal_dot_v1_dot_kernel__gateway__pb2.CancelJobRequest.FromString,
                    response_serializer=eigen_dot_internal_dot_v1_dot_kernel__gateway__pb2.CancelJobResponse.SerializeToString,
            ),
            'GetJobResults': grpc.unary_unary_rpc_method_handler(
                    servicer.GetJobResults,
                    request_deserializer=eigen_dot_internal_dot_v1_dot_kernel__gateway__pb2.GetJobResultsRequest.FromString,
                    response_serializer=eigen_dot_internal_dot_v1_dot_kernel__gateway__pb2.GetJobResultsResponse.SerializeToString,
            ),
            'StreamJobUpdates': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamJobUpdates,
                    request_deserializer=eigen_dot_internal_dot_v1_dot_kernel__gateway__pb2.StreamJobUpdatesRequest.FromString,
                    response_serializer=eigen_dot_internal_dot_v1_dot_kernel__gateway__pb2.StreamJobUpdatesResponse.SerializeToString,
            ),
            'GetDispatchRationale': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDispatchRationale,
                    request_deserializer=eigen_dot_internal_dot_v1_dot_kernel__gateway__pb2.GetDispatchRationaleRequest.FromString,
                    response_serializer=eigen_dot_internal_dot_v1_dot_kernel__gateway__pb2.GetDispatchRationaleResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'eigen.internal.v1.KernelGatewayService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('eigen.internal.v1.KernelGatewayService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class KernelGatewayService:
    """Product 1.0 Wave 2 internal gateway between System API and Kernel.
    Kernel/QRTX is the canonical lifecycle authority.
    Source of truth: RFC 0050, docs/reference/api/grpc-internal.md
    """

    @staticmethod
    def EnqueueJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/eigen.internal.v1.KernelGatewayService/EnqueueJob',
            eigen_dot_internal_dot_v1_dot_kernel__gateway__pb2.EnqueueJobRequest.SerializeToString,
            eigen_dot_internal_dot_v1_dot_kernel__gateway__pb2.EnqueueJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetJobStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/eigen.internal.v1.KernelGatewayService/GetJobStatus',
            eigen_dot_internal_dot_v1_dot_kernel__gateway__pb2.GetJobStatusRequest.SerializeToString,
            eigen_dot_internal_dot_v1_dot_kernel__gateway__pb2.GetJobStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/eigen.internal.v1.KernelGatewayService/CancelJob',
            eigen_dot_internal_dot_v1_dot_kernel__gateway__pb2.CancelJobRequest.SerializeToString,
            eigen_dot_internal_dot_v1_dot_kernel__gateway__pb2.CancelJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetJobResults(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/eigen.internal.v1.KernelGatewayService/GetJobResults',
            eigen_dot_internal_dot_v1_dot_kernel__gateway__pb2.GetJobResultsRequest.SerializeToString,
            eigen_dot_internal_dot_v1_dot_kernel__gateway__pb2.GetJobResultsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamJobUpdates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/eigen.internal.v1.KernelGatewayService/StreamJobUpdates',
            eigen_dot_internal_dot_v1_dot_kernel__gateway__pb2.StreamJobUpdatesRequest.SerializeToString,
            eigen_dot_internal_dot_v1_dot_kernel__gateway__pb2.StreamJobUpdatesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDispatchRationale(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/eigen.internal.v1.KernelGatewayService/GetDispatchRationale',
            eigen_dot_internal_dot_v1_dot_kernel__gateway__pb2.GetDispatchRationaleRequest.SerializeToString,
            eigen_dot_internal_dot_v1_dot_kernel__gateway__pb2.GetDispatchRationaleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
