# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: eigen_api/v1/device_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'eigen_api/v1/device_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from eigen_api.v1 import types_pb2 as eigen__api_dot_v1_dot_types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!eigen_api/v1/device_service.proto\x12\x0c\x65igen.api.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x18\x65igen_api/v1/types.proto\"*\n\x12ListDevicesRequest\x12\x14\n\x0c\x62\x61\x63kend_type\x18\x01 \x01(\t\"@\n\x13ListDevicesResponse\x12)\n\x07\x64\x65vices\x18\x01 \x03(\x0b\x32\x18.eigen.api.v1.DeviceInfo\")\n\x14\x44\x65viceDetailsRequest\x12\x11\n\tdevice_id\x18\x01 \x01(\t\"A\n\x15\x44\x65viceDetailsResponse\x12(\n\x06\x64\x65vice\x18\x01 \x01(\x0b\x32\x18.eigen.api.v1.DeviceInfo\"(\n\x13\x44\x65viceStatusRequest\x12\x11\n\tdevice_id\x18\x01 \x01(\t\"\xfb\x01\n\x14\x44\x65viceStatusResponse\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12*\n\x06status\x18\x02 \x01(\x0e\x32\x1a.eigen.api.v1.DeviceStatus\x12\x13\n\x0bqueue_depth\x18\x03 \x01(\x05\x12\x1a\n\x12\x65stimated_wait_sec\x18\x04 \x01(\x05\x12\x42\n\x08metadata\x18\x05 \x03(\x0b\x32\x30.eigen.api.v1.DeviceStatusResponse.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"O\n\x14ReserveDeviceRequest\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\x13\n\x0bttl_seconds\x18\x02 \x01(\x05\x12\x0f\n\x07purpose\x18\x03 \x01(\t\"_\n\x15ReserveDeviceResponse\x12\x16\n\x0ereservation_id\x18\x01 \x01(\t\x12.\n\nexpires_at\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp2\xf4\x02\n\rDeviceService\x12R\n\x0bListDevices\x12 .eigen.api.v1.ListDevicesRequest\x1a!.eigen.api.v1.ListDevicesResponse\x12[\n\x10GetDeviceDetails\x12\".eigen.api.v1.DeviceDetailsRequest\x1a#.eigen.api.v1.DeviceDetailsResponse\x12X\n\x0fGetDeviceStatus\x12!.eigen.api.v1.DeviceStatusRequest\x1a\".eigen.api.v1.DeviceStatusResponse\x12X\n\rReserveDevice\x12\".eigen.api.v1.ReserveDeviceRequest\x1a#.eigen.api.v1.ReserveDeviceResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'eigen_api.v1.device_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DEVICESTATUSRESPONSE_METADATAENTRY']._loaded_options = None
  _globals['_DEVICESTATUSRESPONSE_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_LISTDEVICESREQUEST']._serialized_start=110
  _globals['_LISTDEVICESREQUEST']._serialized_end=152
  _globals['_LISTDEVICESRESPONSE']._serialized_start=154
  _globals['_LISTDEVICESRESPONSE']._serialized_end=218
  _globals['_DEVICEDETAILSREQUEST']._serialized_start=220
  _globals['_DEVICEDETAILSREQUEST']._serialized_end=261
  _globals['_DEVICEDETAILSRESPONSE']._serialized_start=263
  _globals['_DEVICEDETAILSRESPONSE']._serialized_end=328
  _globals['_DEVICESTATUSREQUEST']._serialized_start=330
  _globals['_DEVICESTATUSREQUEST']._serialized_end=370
  _globals['_DEVICESTATUSRESPONSE']._serialized_start=373
  _globals['_DEVICESTATUSRESPONSE']._serialized_end=624
  _globals['_DEVICESTATUSRESPONSE_METADATAENTRY']._serialized_start=577
  _globals['_DEVICESTATUSRESPONSE_METADATAENTRY']._serialized_end=624
  _globals['_RESERVEDEVICEREQUEST']._serialized_start=626
  _globals['_RESERVEDEVICEREQUEST']._serialized_end=705
  _globals['_RESERVEDEVICERESPONSE']._serialized_start=707
  _globals['_RESERVEDEVICERESPONSE']._serialized_end=802
  _globals['_DEVICESERVICE']._serialized_start=805
  _globals['_DEVICESERVICE']._serialized_end=1177
# @@protoc_insertion_point(module_scope)
