# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from eigen_api.v1 import job_service_pb2 as eigen__api_dot_v1_dot_job__service__pb2
from eigen_api.v1 import types_pb2 as eigen__api_dot_v1_dot_types__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in eigen_api/v1/job_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class JobServiceStub(object):
    """Public job lifecycle service (MVP).
    Source of truth: RFC 0004 + docs/reference/api/grpc-public.md
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitJob = channel.unary_unary(
                '/eigen.api.v1.JobService/SubmitJob',
                request_serializer=eigen__api_dot_v1_dot_job__service__pb2.SubmitJobRequest.SerializeToString,
                response_deserializer=eigen__api_dot_v1_dot_job__service__pb2.JobResponse.FromString,
                _registered_method=True)
        self.GetJobStatus = channel.unary_unary(
                '/eigen.api.v1.JobService/GetJobStatus',
                request_serializer=eigen__api_dot_v1_dot_job__service__pb2.JobStatusRequest.SerializeToString,
                response_deserializer=eigen__api_dot_v1_dot_job__service__pb2.JobStatusResponse.FromString,
                _registered_method=True)
        self.CancelJob = channel.unary_unary(
                '/eigen.api.v1.JobService/CancelJob',
                request_serializer=eigen__api_dot_v1_dot_job__service__pb2.CancelJobRequest.SerializeToString,
                response_deserializer=eigen__api_dot_v1_dot_job__service__pb2.CancelJobResponse.FromString,
                _registered_method=True)
        self.StreamJobUpdates = channel.unary_stream(
                '/eigen.api.v1.JobService/StreamJobUpdates',
                request_serializer=eigen__api_dot_v1_dot_job__service__pb2.JobUpdatesRequest.SerializeToString,
                response_deserializer=eigen__api_dot_v1_dot_types__pb2.JobUpdate.FromString,
                _registered_method=True)
        self.GetJobResults = channel.unary_unary(
                '/eigen.api.v1.JobService/GetJobResults',
                request_serializer=eigen__api_dot_v1_dot_job__service__pb2.JobResultsRequest.SerializeToString,
                response_deserializer=eigen__api_dot_v1_dot_job__service__pb2.JobResultsResponse.FromString,
                _registered_method=True)


class JobServiceServicer(object):
    """Public job lifecycle service (MVP).
    Source of truth: RFC 0004 + docs/reference/api/grpc-public.md
    """

    def SubmitJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetJobStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamJobUpdates(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetJobResults(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_JobServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitJob': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitJob,
                    request_deserializer=eigen__api_dot_v1_dot_job__service__pb2.SubmitJobRequest.FromString,
                    response_serializer=eigen__api_dot_v1_dot_job__service__pb2.JobResponse.SerializeToString,
            ),
            'GetJobStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetJobStatus,
                    request_deserializer=eigen__api_dot_v1_dot_job__service__pb2.JobStatusRequest.FromString,
                    response_serializer=eigen__api_dot_v1_dot_job__service__pb2.JobStatusResponse.SerializeToString,
            ),
            'CancelJob': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelJob,
                    request_deserializer=eigen__api_dot_v1_dot_job__service__pb2.CancelJobRequest.FromString,
                    response_serializer=eigen__api_dot_v1_dot_job__service__pb2.CancelJobResponse.SerializeToString,
            ),
            'StreamJobUpdates': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamJobUpdates,
                    request_deserializer=eigen__api_dot_v1_dot_job__service__pb2.JobUpdatesRequest.FromString,
                    response_serializer=eigen__api_dot_v1_dot_types__pb2.JobUpdate.SerializeToString,
            ),
            'GetJobResults': grpc.unary_unary_rpc_method_handler(
                    servicer.GetJobResults,
                    request_deserializer=eigen__api_dot_v1_dot_job__service__pb2.JobResultsRequest.FromString,
                    response_serializer=eigen__api_dot_v1_dot_job__service__pb2.JobResultsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'eigen.api.v1.JobService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('eigen.api.v1.JobService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class JobService(object):
    """Public job lifecycle service (MVP).
    Source of truth: RFC 0004 + docs/reference/api/grpc-public.md
    """

    @staticmethod
    def SubmitJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/eigen.api.v1.JobService/SubmitJob',
            eigen__api_dot_v1_dot_job__service__pb2.SubmitJobRequest.SerializeToString,
            eigen__api_dot_v1_dot_job__service__pb2.JobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetJobStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/eigen.api.v1.JobService/GetJobStatus',
            eigen__api_dot_v1_dot_job__service__pb2.JobStatusRequest.SerializeToString,
            eigen__api_dot_v1_dot_job__service__pb2.JobStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/eigen.api.v1.JobService/CancelJob',
            eigen__api_dot_v1_dot_job__service__pb2.CancelJobRequest.SerializeToString,
            eigen__api_dot_v1_dot_job__service__pb2.CancelJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamJobUpdates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/eigen.api.v1.JobService/StreamJobUpdates',
            eigen__api_dot_v1_dot_job__service__pb2.JobUpdatesRequest.SerializeToString,
            eigen__api_dot_v1_dot_types__pb2.JobUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetJobResults(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/eigen.api.v1.JobService/GetJobResults',
            eigen__api_dot_v1_dot_job__service__pb2.JobResultsRequest.SerializeToString,
            eigen__api_dot_v1_dot_job__service__pb2.JobResultsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
