# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from eigen.api.v1 import knowledge_base_service_pb2 as eigen_dot_api_dot_v1_dot_knowledge__base__service__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in eigen/api/v1/knowledge_base_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class KnowledgeBaseServiceStub:
    """Knowledge Base API contract v1.
    Source of truth: RFC 0034.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UpsertRecord = channel.unary_unary(
                '/eigen.api.v1.KnowledgeBaseService/UpsertRecord',
                request_serializer=eigen_dot_api_dot_v1_dot_knowledge__base__service__pb2.UpsertRecordRequest.SerializeToString,
                response_deserializer=eigen_dot_api_dot_v1_dot_knowledge__base__service__pb2.UpsertRecordResponse.FromString,
                _registered_method=True)
        self.BatchUpsertRecords = channel.unary_unary(
                '/eigen.api.v1.KnowledgeBaseService/BatchUpsertRecords',
                request_serializer=eigen_dot_api_dot_v1_dot_knowledge__base__service__pb2.BatchUpsertRecordsRequest.SerializeToString,
                response_deserializer=eigen_dot_api_dot_v1_dot_knowledge__base__service__pb2.BatchUpsertRecordsResponse.FromString,
                _registered_method=True)
        self.QueryRecords = channel.unary_unary(
                '/eigen.api.v1.KnowledgeBaseService/QueryRecords',
                request_serializer=eigen_dot_api_dot_v1_dot_knowledge__base__service__pb2.QueryRecordsRequest.SerializeToString,
                response_deserializer=eigen_dot_api_dot_v1_dot_knowledge__base__service__pb2.QueryRecordsResponse.FromString,
                _registered_method=True)
        self.GetRecord = channel.unary_unary(
                '/eigen.api.v1.KnowledgeBaseService/GetRecord',
                request_serializer=eigen_dot_api_dot_v1_dot_knowledge__base__service__pb2.GetRecordRequest.SerializeToString,
                response_deserializer=eigen_dot_api_dot_v1_dot_knowledge__base__service__pb2.GetRecordResponse.FromString,
                _registered_method=True)
        self.AppendDecisionLog = channel.unary_unary(
                '/eigen.api.v1.KnowledgeBaseService/AppendDecisionLog',
                request_serializer=eigen_dot_api_dot_v1_dot_knowledge__base__service__pb2.AppendDecisionLogRequest.SerializeToString,
                response_deserializer=eigen_dot_api_dot_v1_dot_knowledge__base__service__pb2.AppendDecisionLogResponse.FromString,
                _registered_method=True)
        self.QueryDecisionLogs = channel.unary_unary(
                '/eigen.api.v1.KnowledgeBaseService/QueryDecisionLogs',
                request_serializer=eigen_dot_api_dot_v1_dot_knowledge__base__service__pb2.QueryDecisionLogsRequest.SerializeToString,
                response_deserializer=eigen_dot_api_dot_v1_dot_knowledge__base__service__pb2.QueryDecisionLogsResponse.FromString,
                _registered_method=True)


class KnowledgeBaseServiceServicer:
    """Knowledge Base API contract v1.
    Source of truth: RFC 0034.
    """

    def UpsertRecord(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchUpsertRecords(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryRecords(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRecord(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AppendDecisionLog(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryDecisionLogs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KnowledgeBaseServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UpsertRecord': grpc.unary_unary_rpc_method_handler(
                    servicer.UpsertRecord,
                    request_deserializer=eigen_dot_api_dot_v1_dot_knowledge__base__service__pb2.UpsertRecordRequest.FromString,
                    response_serializer=eigen_dot_api_dot_v1_dot_knowledge__base__service__pb2.UpsertRecordResponse.SerializeToString,
            ),
            'BatchUpsertRecords': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchUpsertRecords,
                    request_deserializer=eigen_dot_api_dot_v1_dot_knowledge__base__service__pb2.BatchUpsertRecordsRequest.FromString,
                    response_serializer=eigen_dot_api_dot_v1_dot_knowledge__base__service__pb2.BatchUpsertRecordsResponse.SerializeToString,
            ),
            'QueryRecords': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryRecords,
                    request_deserializer=eigen_dot_api_dot_v1_dot_knowledge__base__service__pb2.QueryRecordsRequest.FromString,
                    response_serializer=eigen_dot_api_dot_v1_dot_knowledge__base__service__pb2.QueryRecordsResponse.SerializeToString,
            ),
            'GetRecord': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRecord,
                    request_deserializer=eigen_dot_api_dot_v1_dot_knowledge__base__service__pb2.GetRecordRequest.FromString,
                    response_serializer=eigen_dot_api_dot_v1_dot_knowledge__base__service__pb2.GetRecordResponse.SerializeToString,
            ),
            'AppendDecisionLog': grpc.unary_unary_rpc_method_handler(
                    servicer.AppendDecisionLog,
                    request_deserializer=eigen_dot_api_dot_v1_dot_knowledge__base__service__pb2.AppendDecisionLogRequest.FromString,
                    response_serializer=eigen_dot_api_dot_v1_dot_knowledge__base__service__pb2.AppendDecisionLogResponse.SerializeToString,
            ),
            'QueryDecisionLogs': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryDecisionLogs,
                    request_deserializer=eigen_dot_api_dot_v1_dot_knowledge__base__service__pb2.QueryDecisionLogsRequest.FromString,
                    response_serializer=eigen_dot_api_dot_v1_dot_knowledge__base__service__pb2.QueryDecisionLogsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'eigen.api.v1.KnowledgeBaseService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('eigen.api.v1.KnowledgeBaseService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class KnowledgeBaseService:
    """Knowledge Base API contract v1.
    Source of truth: RFC 0034.
    """

    @staticmethod
    def UpsertRecord(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/eigen.api.v1.KnowledgeBaseService/UpsertRecord',
            eigen_dot_api_dot_v1_dot_knowledge__base__service__pb2.UpsertRecordRequest.SerializeToString,
            eigen_dot_api_dot_v1_dot_knowledge__base__service__pb2.UpsertRecordResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchUpsertRecords(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/eigen.api.v1.KnowledgeBaseService/BatchUpsertRecords',
            eigen_dot_api_dot_v1_dot_knowledge__base__service__pb2.BatchUpsertRecordsRequest.SerializeToString,
            eigen_dot_api_dot_v1_dot_knowledge__base__service__pb2.BatchUpsertRecordsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryRecords(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/eigen.api.v1.KnowledgeBaseService/QueryRecords',
            eigen_dot_api_dot_v1_dot_knowledge__base__service__pb2.QueryRecordsRequest.SerializeToString,
            eigen_dot_api_dot_v1_dot_knowledge__base__service__pb2.QueryRecordsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRecord(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/eigen.api.v1.KnowledgeBaseService/GetRecord',
            eigen_dot_api_dot_v1_dot_knowledge__base__service__pb2.GetRecordRequest.SerializeToString,
            eigen_dot_api_dot_v1_dot_knowledge__base__service__pb2.GetRecordResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AppendDecisionLog(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/eigen.api.v1.KnowledgeBaseService/AppendDecisionLog',
            eigen_dot_api_dot_v1_dot_knowledge__base__service__pb2.AppendDecisionLogRequest.SerializeToString,
            eigen_dot_api_dot_v1_dot_knowledge__base__service__pb2.AppendDecisionLogResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryDecisionLogs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/eigen.api.v1.KnowledgeBaseService/QueryDecisionLogs',
            eigen_dot_api_dot_v1_dot_knowledge__base__service__pb2.QueryDecisionLogsRequest.SerializeToString,
            eigen_dot_api_dot_v1_dot_knowledge__base__service__pb2.QueryDecisionLogsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
