# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc
import warnings

from eigen.internal.v1 import neuro_symbolic_service_pb2 as eigen_dot_internal_dot_v1_dot_neuro__symbolic__service__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in eigen/internal/v1/neuro_symbolic_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NeuroSymbolicServiceStub(object):
    """Internal DPDA model service contract v1.
    Source of truth: DPDA-NEURO-01.
    """
    def __init__(self, channel):
        """Constructor.
        Args:
            channel: A grpc.Channel.
        """
        self.ScoreCompilationPlan = channel.unary_unary(
            '/eigen.internal.v1.NeuroSymbolicService/ScoreCompilationPlan',
                request_serializer=eigen_dot_internal_dot_v1_dot_neuro__symbolic__service__pb2.ScoreCompilationPlanRequest.SerializeToString,
                response_deserializer=eigen_dot_internal_dot_v1_dot_neuro__symbolic__service__pb2.ScoreCompilationPlanResponse.FromString,
                _registered_method=True)


class NeuroSymbolicServiceServicer(object):
    """Internal DPDA model service contract v1.
    Source of truth: DPDA-NEURO-01.
    """
    def ScoreCompilationPlan(self, request, context):
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError()


def add_NeuroSymbolicServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'ScoreCompilationPlan': grpc.unary_unary_rpc_method_handler(
                    servicer.ScoreCompilationPlan,
                    request_deserializer=eigen_dot_internal_dot_v1_dot_neuro__symbolic__service__pb2.ScoreCompilationPlanRequest.FromString,
                    response_serializer=eigen_dot_internal_dot_v1_dot_neuro__symbolic__service__pb2.ScoreCompilationPlanResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'eigen.internal.v1.NeuroSymbolicService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('eigen.internal.v1.NeuroSymbolicService', rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class NeuroSymbolicService(object):
    """Internal DPDA model service contract v1.
    Source of truth: DPDA-NEURO-01.
    """

    @staticmethod
    def ScoreCompilationPlan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/eigen.internal.v1.NeuroSymbolicService/ScoreCompilationPlan',
            eigen_dot_internal_dot_v1_dot_neuro__symbolic__service__pb2.ScoreCompilationPlanRequest.SerializeToString,
            eigen_dot_internal_dot_v1_dot_neuro__symbolic__service__pb2.ScoreCompilationPlanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
